services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      - SSH_AUTH_SOCK="${SSH_AUTH_SOCK}"
    # env_file: .devcontainer.env
    volumes:
      - ../..:/workspaces:cached
      - ${SSH_AUTH_SOCK}:${SSH_AUTH_SOCK}

  db:
    # https://hub.docker.com/_/postgres/
    build:
      context: .
      dockerfile: postgres.Dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:9.0
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "13913:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin:
  caddy_data:
  caddy_config:
  # zo_data:
